### ISSUE TITLE
No explanation what Subscribe button does

### ISSUE THREAD

**Issue by crtahlin** [swarmanda/swarmy-frontend#2]
Does clicking the Subscribe button on page https://swarmy.cloud/app/billing (and following through with payment) actually create a recurring monthly payment on the credit card?

If so, how does one cancel it?

Some docs would be needed about that or a short explanation text near the button.

**Comment by swarmanda** [comment]
Hi @crtahlin, thanks for reporting this issue.

I added a text above the Subscribe button so the functionality is more transparent.
I also created a FAQ page where it is explaned in more detail: https://swarmy.cloud/faq

**Comment by crtahlin** [comment]
The "cog" is not very visible/ intuitive to find or use for canceling. Would suggest:
- add label "Settings next to the icon (perhaps move both to right side of window)
- change "You can cancel the subscription anytime, you will be able to access the paid services until the end of the billing period." --> "You can cancel the subscription anytime via Settings menu, you will be able to access the paid services until the end of the billing period.

**Comment by crtahlin** [comment]
Also, selecting "Cancel", the popup appears: 
![image](https://github.com/user-attachments/assets/11c669cc-a43c-41dd-a934-5429d46f2df3)

It says I will not be able to upload after canceling. But the main page says I will be able to use until the end of billing period. So what is true? One of the texts should be modified.

**Comment by crtahlin** [comment]
Also, there should be a link to the [FAQ](https://swarmy.cloud/faq) from the app webpage (perhaps bottom left).
